---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Create index.html
  template:
    src: index.html.j2
    dest: "{{ html_file }}"
    mode: '0644'

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf }}"
    mode: '0644'
  notify:
    - restart nginx

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: true
